apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |-
    user  nginx;
    worker_processes  1;

    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;

    events {
        worker_connections  1024;
    }

    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';

        access_log  /var/log/nginx/access.log  main;

        sendfile        on;
        keepalive_timeout  65;

        upstream sonar {
            server 127.0.0.1:9000;
        }

        server {
            listen 80;
            
            client_max_body_size 20M;

            location / {
                proxy_pass         http://sonar;
                proxy_redirect     off;
            }
        }
       
        server {
           listen 443 ssl;
           
           client_max_body_size 20M;
        
           ssl_certificate /etc/tls/tls.crt;
           ssl_certificate_key /etc/tls/tls.key;

           proxy_set_header X-Forwarded-Proto https;

           ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
           ssl_ciphers HIGH:!aNULL:!MD5;
           ssl_prefer_server_ciphers on;

           ssl_session_cache shared:SSL:10m;
           ssl_session_timeout 10m;
           ssl_stapling on;

           location / {
               proxy_pass http://sonar;
       }
        }
    }