apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonar-ext-pv-claim
  labels:
    group: sonarqube
    app: sonar
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi